# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: SST
email: hello@sst.dev
jobs_email: jobs@sst.dev
description: > # this means to ignore newlines until "baseurl:"
  Build modern full-stack applications on AWS.
description_full: >
  An open source framework for building modern full-stack applications on AWS.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sst.dev" # the base hostname & protocol for your site, e.g. http://example.com

demo_url: "https://demo.sst.dev"

github_repo: "https://github.com/AnomalyInnovations/serverless-stack-com"
github_edit_prefix: "/edit/master/"
github_history_prefix: "/commits/master/"
github_issues_prefix: "/issues/"

backend_github_repo: "https://github.com/AnomalyInnovations/serverless-stack-demo-api"
frontend_github_repo: "https://github.com/AnomalyInnovations/serverless-stack-demo-client"
frontend_fb_login_github_repo: "https://github.com/AnomalyInnovations/serverless-stack-demo-fb-login-client"
frontend_user_mgmt_github_repo: "https://github.com/AnomalyInnovations/serverless-stack-demo-user-mgmt-client"
backend_ext_api_github_repo: "https://github.com/AnomalyInnovations/serverless-stack-demo-ext-api"
backend_ext_resources_github_repo: "https://github.com/AnomalyInnovations/serverless-stack-demo-ext-resources"

sst_github_repo: "https://github.com/sst/sst"
sst_github_examples_prefix: "/tree/master/examples/"
sst_demo_repo: "https://github.com/sst/demo-notes-app"

seed_url: "https://seed.run"
survey_url: "https://serverless-stack.typeform.com/to/xiPdCW"

google_analytics: "UA-3536629-11"

docs_url: "https://docs.sst.dev"
v1_conf_url: "https://v1conf.sst.dev"
console_url: "https://console.sst.dev"
old_console_url: "https://old.console.sst.dev"
forum_url: "https://discourse.sst.dev"
forum_thread_prefix: "/t/"
patreon_url: "https://www.patreon.com/serverless_stack"
github_sponsor_url: "https://github.com/sponsors/jayair"
twitter: "ServerlessStack"
twitter_url: "https://twitter.com/sst_dev"
slack_invite_url: "https://sst.dev/slack"
discord_invite_url: "https://discord.gg/sst"
linkedin_url: "https://www.linkedin.com/company/sst-dev"
youtube_url: "https://www.youtube.com/c/sst-dev"

social_cards_url: "https://social-cards.sst.dev"

permalink: /blog/:title:output_ext

stats:
  newsletter: "90,000"
  newsletter_short: "90k"
  discord: "5500"
  github: "17000"
  github_short: "17k"

collections:
  chapters:
    output: true
  examples:
    output: true

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
# Front Matter defaults
#defaults:
#  - scope:
#      path: ""
#    values:
#      image: serverless-stack-lander/index.png
